name: deploy lambda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run tests
      run: |
        python -m unittest tests/hellotest.py
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Docker Build
      run: |
        docker build -t 587838441384.dkr.ecr.us-west-2.amazonaws.com/hello-lambda:latest .
    - name: Login to ECR
      uses: docker/login-action@v1
      with:
        registry: 587838441384.dkr.ecr.us-west-2.amazonaws.com
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Push
      run: |
        docker push 587838441384.dkr.ecr.us-west-2.amazonaws.com/hello-lambda:latest
