name: test this

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: test this out
      shell: bash
      env:
        SUPER_SECRET: ${{ secrets.POLLER_AWS_REGION }}
      run: |
        echo "$SUPER_SECRET"